import Head from "next/head";
import { Canvas } from "~/components/canvas";

export default function Home() {
  // const hello = api.post.hello.useQuery({ text: "from tRPC" });
  //
  // const latestPost = api.post.getLatest.useQuery()

  return (
    <>
      <Head>
        <title>Drawy</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col">
        <h1 className="text-5xl font-extrabold text-black sm:text-[5rem]">
          Drawy
        </h1>
        <Canvas />
      </main>
    </>
  );
}
