import Head from "next/head";
import { useState } from "react";
import { Canvas } from "~/components/canvas";
import { ToolSelection } from "~/components/toolSelection";
import { type Tool } from "~/utils/tools/tools";

export default function Home() {
  const [selectedTool, setTool] = useState<Tool>("SELECT");

  return (
    <>
      <Head>
        <title>Drawy</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col">
        <div className="flex">
          <h1 className="text-5xl font-extrabold text-black sm:text-[5rem]">
            Drawy
          </h1>
          <ToolSelection
            selectedTool={selectedTool}
            onSelect={(value: string) => setTool(value as Tool)}
          />
        </div>
        <Canvas tool={selectedTool} />
      </main>
    </>
  );
}
